name: test
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: setup
        run: |
          if echo ${{ github.ref }} | grep -q "-"; then PRERELEASE=true; else PRERELEASE=false; fi
          echo "::set-output name=prerelease::${PRERELEASE}"
